"""
Metrics Collection Module
Exports Prometheus metrics for monitoring
"""

import logging
from datetime import datetime
from typing import Optional

from prometheus_client import Counter, Gauge, Histogram, Summary, generate_latest, REGISTRY
from fastapi import Request

logger = logging.getLogger(__name__)

# Request metrics
REQUEST_COUNT = Counter(
    'http_requests_total',
    'Total HTTP requests',
    ['method', 'endpoint', 'status_code']
)

REQUEST_DURATION = Histogram(
    'http_request_duration_seconds',
    'HTTP request duration in seconds',
    ['method', 'endpoint'],
    buckets=(0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0, 7.5, 10.0)
)

REQUEST_SIZE = Summary(
    'http_request_size_bytes',
    'HTTP request size in bytes',
    ['method', 'endpoint']
)

RESPONSE_SIZE = Summary(
    'http_response_size_bytes',
    'HTTP response size in bytes',
    ['method', 'endpoint', 'status_code']
)

# Ollama metrics
OLLAMA_GENERATION_DURATION = Histogram(
    'ollama_generation_duration_seconds',
    'Ollama generation duration in seconds',
    ['model'],
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0)
)

OLLAMA_TOKENS_GENERATED = Counter(
    'ollama_tokens_generated_total',
    'Total tokens generated by Ollama',
    ['model']
)

OLLAMA_TOKENS_PROCESSED = Counter(
    'ollama_tokens_processed_total',
    'Total tokens processed by Ollama',
    ['model']
)

OLLAMA_GENERATION_ERRORS = Counter(
    'ollama_generation_errors_total',
    'Total Ollama generation errors',
    ['model', 'error_type']
)

# Database metrics
DB_QUERY_DURATION = Histogram(
    'db_query_duration_seconds',
    'Database query duration in seconds',
    ['operation', 'table'],
    buckets=(0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0)
)

DB_CONNECTIONS = Gauge(
    'db_connections_active',
    'Active database connections'
)

DB_POOL_SIZE = Gauge(
    'db_pool_size',
    'Database connection pool size'
)

# Cache metrics
CACHE_HITS = Counter(
    'cache_hits_total',
    'Total cache hits',
    ['cache_type', 'operation']
)

CACHE_MISSES = Counter(
    'cache_misses_total',
    'Total cache misses',
    ['cache_type', 'operation']
)

CACHE_EVICTIONS = Counter(
    'cache_evictions_total',
    'Total cache evictions',
    ['cache_type']
)

# Authentication metrics
AUTH_ATTEMPTS = Counter(
    'auth_attempts_total',
    'Total authentication attempts',
    ['method', 'result']
)

AUTH_TOKENS_ISSUED = Counter(
    'auth_tokens_issued_total',
    'Total tokens issued',
    ['token_type']
)

ACTIVE_SESSIONS = Gauge(
    'active_sessions',
    'Number of active sessions'
)

# Rate limiting metrics
RATE_LIMIT_EXCEEDED = Counter(
    'rate_limit_exceeded_total',
    'Total rate limit exceeded events',
    ['endpoint']
)

# Business metrics
CONVERSATIONS_CREATED = Counter(
    'conversations_created_total',
    'Total conversations created'
)

DOCUMENTS_INDEXED = Counter(
    'documents_indexed_total',
    'Total documents indexed'
)

RAG_QUERIES = Counter(
    'rag_queries_total',
    'Total RAG queries executed'
)

RAG_QUERY_LATENCY = Histogram(
    'rag_query_latency_seconds',
    'RAG query latency in seconds',
    buckets=(0.1, 0.5, 1.0, 2.0, 5.0, 10.0)
)


def get_metrics_summary() -> dict:
    """
    Get summary of all metrics
    
    Returns:
        Dictionary of metric summaries
    """
    return {
        "http_requests": REQUEST_COUNT._metrics,
        "ollama_generation": OLLAMA_GENERATION_DURATION._metrics,
        "cache_hits": CACHE_HITS._metrics,
        "cache_misses": CACHE_MISSES._metrics,
        "auth_attempts": AUTH_ATTEMPTS._metrics,
    }


class MetricsMiddleware:
    """Context manager for metrics collection"""
    
    def __init__(self, request: Request):
        """Initialize metrics context"""
        self.request = request
        self.start_time = datetime.now()
    
    def __enter__(self):
        """Start metrics collection"""
        return self
    
    def __exit__(self, exc_type, exc_val, exc_tb):
        """End metrics collection"""
        pass


def export_metrics() -> bytes:
    """
    Export metrics in Prometheus format
    
    Returns:
        Metrics in Prometheus text format
    """
    return generate_latest(REGISTRY)
